### ISSUE TITLE
Pulling a Single File (Short Term Goal)

### ISSUE THREAD

**Issue by MRuvinshteyn** [jennifer4569/CoCode#4]
A function needs to be added to pull a single file of the user's choice from the server.

Using this feature to display to the user all files that have been pushed by him/her. (Pulling a file that displays all the files that's been pushed, and having the GUI interpret that in a file browser)

**Comment by jennifer4569** [comment]
Using this feature to display to the user all files that have been pushed by him/her. (Pulling a file that displays all the files that's been pushed, and having the GUI interpret that in a file browser)

**Comment by jennifer4569** [comment]
Richard started this, I'll finish it by connecting it to the server.

**Comment by richard-le** [comment]
I have implemented a c++ program for that.
Usage: ./a.out [filename] [server directory] [client directory]
client will pull the file from the server directory and save into the client directory.

**Comment by jennifer4569** [comment]
Finished connecting it with the server.
